In [2]:
import numpy as np


In [3]:
a=[1,2,3]

In [4]:
a

[1, 2, 3]

In [5]:
b=[1,2,3]

In [6]:
b

[1, 2, 3]

In [7]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [8]:
np.multiply(a,b)

array([1, 4, 9])

In [9]:
a.shape


AttributeError: 'list' object has no attribute 'shape'

In [32]:
a = np.array([[1,2,3],[4,5,6]])

In [33]:
b = np.array([[1,2,3],[4,5,6]])

In [35]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [37]:
a*b/10

array([[ 0.1,  0.4,  0.9],
       [ 1.6,  2.5,  3.6]])

In [23]:
b.shape[0]

3

In [24]:
b.shape[1]

1